name: "⚒ Generating Duplicate Report"

on:
  pull_request_target:
    paths: '**.ir'
    
jobs:
  dupe-checker:
    name: "🎭 Looking for possible duplicates"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v3
        with:
          repository: 'darmiel/flipper-scripts'
          path: flipper-scripts
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.7
        with:
          files: "**/*.ir"
          separator: "\n"
          
      - name: Save changed file names to file
        run: echo '${{ steps.changed-files.outputs.added_files }}' > added_file_list.txt
        
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
        
      - name: Generate Report
        id: run
        run: | 
          export PYTHONPATH="$PWD/flipper-scripts"
          echo "OUTPUT<<EOF" >> $GITHUB_OUTPUT
          python flipper-scripts/infrared/duplicate_finder.py file:added_file_list.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment Report
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.run.outputs.OUTPUT }}
        with:
          message: |
            <details>
              <summary>🕶 Duplicates Report</summary>
              ${{ steps.run.outputs.OUTPUT }}  
            </details>
